### ISSUE TITLE
cases/credit_scoring_problem.py freezes and does not show any logs

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#127]
Current version of the script seems weird: it doesn't print any logs even if i set max_lead_time = 1 min and seems to be freezed.
![image](https://user-images.githubusercontent.com/7864250/86893446-4df5a780-c10a-11ea-8814-e853a6d79133.png)

**Comment by nicl-nno** [comment]
По итогам обсуждения решение проблемы можно начать с:

1. Более подробного логирования операций в ходе обработки одной популяции (можно только при включенном verbose-выводе);
2. Добавления более ранних проверок на срок окончания таймера (в т.ч. в цикл обучения single-моделей);
3. Профилировки - возможно, это время тратится не только на обучение моделей.

Если это поможет тем, у кого наблюдались зависания - можно думать, как улучшить таймер.
