### ISSUE TITLE
Implement export of the composite model structure to json

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#129]
Фреймворк "Федот" позволяет генерировать композитные модели со сложной структурой (в терминологии фреймворка мы называем их цепочка - Chain) и выполнять их тестирование. Однако, для практических задач важно также "отчуждать" эти модели от фреймворка и использовать независимо от него.

Поэтому нужно реализовать экспорт Chain в виде описания на json-подобном предметно-ориентированном языке, удобном для человеческого восприятия.

1. Json-описание должно содержать полное представление структуры связей между моделями и гиперпараметров каждой из моделей.
2. Должны быть реализованы и покрыты тестами методы, обеспечивающие преобразование Chain->json и json->Chain.

**Comment by J3FALL** [comment]
А что насчет импорта/экспорта еще и весов обученных моделей?
Это позволит реализовать то, что мы давно называли "атомизацией" цепочек.
При этом интерфейс будет идентичным.

**Comment by nicl-nno** [comment]
>А что насчет импорта/экспорта еще и весов обученных моделей?

Я не очень представляю, как можно экспортировать веса произвольных моделей в текстовом виде. 

Для воспроизводимости обучения в вышеописанный JSON можно добавить поле со ссылкой на pickle-файл, в котором сохранена обученная модель, взятая из EvaluationStrategy.

Для атомизации вообще достаточно сохранять цепочку целиком (вот [тут ](https://github.com/nccr-itmo/FEDOT/pull/83)я делал прототип такой реализации для старого репозитория) в pickle-виде, но конечно json-представление будет выглядеть гораздо красивее.

Насчет ChainTemplate не оч. понял, какие новые возможности это даёт. 
Т.е. в твоём варианте чтобы экспортировать Chain в текст, нужно будет сначала преобразовать Chain в ChainTemplate, а потом уже ChainTemplate в json?

**Comment by BarabanovaIrina** [comment]
По итогам всех обсуждений, идея реализации данной задачи такая:

Этап I
1. Создать объект, который сам сможет пройтись по реальной цепочке, собрать json-like описание цепочки, включающий характеристики (глубина, длина и др.), модели в нодах типа: "model_id: dumped_model.h5". 
2. По возможности сохранить это все в каком-то архивном формате.
3. Сделать десериализацию, т.е. прочитать с диска json-файл, собрать цепочку, вставить в нее обученные модели.

Этап II
На данный момент существует ChainTemplate в примитивном формате. Идея такая, что этот объект хранит параметры цепочки и какие-то ее особенности, но не всю обученную цепочку с данными. Что-то типа  упрощенного интерфейса (view) для цепочки . Это нужно для того, чтобы а) не усложняем код ядра б) не усложнять жизнь сложной логикой моделей и хранить структуру и обученные модели отдельно в) избежать проблем с десериализацией pickle-объектов при изменении кода фреймворка.  В связи с этим:

1. Пересмотреть реализацию ChainTemplate таким образом, чтобы была возможность перехода Chain->ChainTemplate->JSON и обратно. Промежуточный этап как раз отделяет структуру.

**Comment by J3FALL** [comment]
Немного поправлю: ChainTemplate как отдельного объекта у нас в коде нет.
Но есть ModelTemplate и несколько функций, при помощи которых можно превратить список ModelTemplat-ов в Chain.

Код можно посмотреть, например, [здесь](https://github.com/nccr-itmo/FEDOT/blob/master/utilities/synthetic/chain_template.py).
