### ISSUE TITLE
Implements financial/economic case

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#130]
- Необходимо изучить наборы данных из финансово-экономической сферы, представленные в рамках соревнований Kaggle (или иных источников).
- Из них нужно выбрать несколько наборов данных, которые сводятся к задачам прогнозирования временных рядов (хотя начать можно с более простых задач классификации регрессии для случайной величины)
- Датасеты и связанные с ними примеры должны бы максимально "нетривиальные", т.к. если задача уже решается с оч. высокой точностью существующими методами - это не слишком интересно.
- Затем необходимо выполнить решение этих задач, используя функциональность фреймворка

**Comment by nicl-nno** [comment]
Если не получится найти каких-то особенно интересных датасеты - есть вот такой запасной вариант, пусть и не совсем финансово-экономический.

https://data.london.gov.uk/dataset/smartmeter-energy-use-data-in-london-households

Это временные ряды потребления электроэнергии в лондонских домах.
Там есть и сезонность и другие виды переиодичности. Также можно использовать доп. данные, вроде рядов температуры воздуха.

**Comment by timur9831** [comment]
- Был выбран следующий набор данных: https://www.kaggle.com/mlg-ulb/creditcardfraud
 Рассматривается задача классификации, выявление мошеннических операций с банковскими картами. 
 Цель: решить данную задачу с помощью функциональности фреймворка FEDOT. 

- Так же будут имплементированы методы для прогнозирования финансовых временных рядов, такие как VAR и GARCH. 
 Данная задача достаточно актуальна, и позволит получить новые виды/комбинации моделей которые будут в лучшей 
 степени описывать данные с помощью фреймворка FEDOT.

**Comment by J3FALL** [comment]
The task seems to be outdated, therefore closed.
