### ISSUE TITLE
Allow composer to return several diverse chains

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#149]
Now the composer allows to return only one best found solution. Hovewer, it is useful to obtain several solutions with different genotype and similar phenotype (or the Pareto frontier for the multiobjective case).

Finally, the obtained diverce solutions can be combined to multi-chain ensemble (implmented as a new chain) in order to increase the quality of the prediction.

**Comment by J3FALL** [comment]
Solved via #215 ?
