### ISSUE TITLE
Implement gap filling functionality

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#153]
The gap filiing functionality should be implemented on a basis of ts-forecasting-new branch.

The metocean data should be used as example.

Comment: #122 should be merged first

**Comment by Dreamlone** [comment]
Used the tsforecasting-new branch. Added a [script](https://github.com/nccr-itmo/FEDOT/blob/ts-gapfilling-new/examples/time_series_gapfilling.py ) with an example of filling in gaps on synthetic data.

Perhaps I should move the implementation of the gapfiller class to another location
