### ISSUE TITLE
Hyperopt was not found in requirements.txt

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#161]
In [tuner_adapter.py](https://github.com/nccr-itmo/FEDOT/blob/master/core/models/tuning/tuner_adapter.py) hyperopt module is imported but it is not presented in requirements.txt

**Comment by nicl-nno** [comment]
Но врод он есть там:

![image](https://user-images.githubusercontent.com/5711814/95775697-90132400-0ccb-11eb-89aa-a8b5e0ccab80.png)
https://github.com/nccr-itmo/FEDOT/blob/master/requirements.txt

**Comment by J3FALL** [comment]
Да, отбой, не в ту ветку смотрел)
