### ISSUE TITLE
Reorganize test directory

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#165]
Currently, in [core ](https://github.com/nccr-itmo/FEDOT/tree/master/core) module we have several logic submodules (composer, repository, models). However, in [test](https://github.com/nccr-itmo/FEDOT/tree/master/test) directory all scripts don't organized at all.
In the issue, it is planned to:
- Combine scripts in test directory according to core module hierarchy
- Make sure that pytest runs all tests correctly in Pycharm/console on Windows/Mac/etc.
- Make sure that Travis is able to successfully run tests in a cloud

**Comment by nicl-nno** [comment]
Я делал попытку реогранизовать тесты в рамках https://github.com/nccr-itmo/FEDOT/tree/ts-forecasting-new/test но выглядит всё ещё не слишком удобно.

**Comment by J3FALL** [comment]
Хм, да в принципе норм, всяко лучше сейчас в мастере.

Fixed by #138.
