### ISSUE TITLE
Implement atomisation of the composite model

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#166]
One of the Fedot ideas is the "atomization" of the composite models - so the composite model can be used as a simple atomic model during composition, fitting, and prediction in the chain.

![image](https://user-images.githubusercontent.com/5711814/96703135-2cf45200-139b-11eb-9496-71d1d884c163.png)

The naive implementation of atomization is available at https://github.com/nccr-itmo/FEDOT/pull/83
but now it should be implemented using model export functionality and the model's repository features.

**Comment by J3FALL** [comment]
Обсудили с Глебом, разбили эту задачу на несколько более мелких.
"Пока предлагаю тебе сфокусироваться этом: сделать фичу, позволяющую преобразовывать цепочку в отдельный подкласс Model, чтобы потом можно было из нее составить отдельную цепочку и ее просчитать.
Соответственно, в первом приближении, нужно сделать что-то такое:
- Создать новый подкласс Model - ChainModel/AtomizedChain
- Реализовать функцию-конвертер Chain -> AtomizedChain - скорее всего, это будет даже не конвертер, а просто конструктор AtomizedChain будет принимать объект класса Chain, которому внутри будут делегироваться методы fit/predict.
- Убедиться, что комплексные цепочки (цепочка, в которой внутри есть еще одна цепочка) вычисляются

Следующим шагом - подумаем, как изменить экспорт и импорт цепочек, чтобы вложенные цепочки тоже можно было выгружать в json.
Дальше - расширим логику композера так, чтобы он мог работать с вложенными цепочками
Ну а в конце решим 2 вопроса: что делать с весами таких моделей и нужно ли дорабатывать ModelTypesRepository так, чтобы он мог поддерживать такие "сохраненные" цепочки."
