### ISSUE TITLE
Refactor "if verbose" logic in core classes

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#170]
In core classes (such as Chain, Node, Model, etc.) we have an optional key `verbose = True`, and depending on its value logs are either printed in console or not. However, it is required to add dublicated if/else constructions in code (see [example](https://github.com/nccr-itmo/FEDOT/blob/f74128329de8be91553e641af69689c2ce027b95/core/composer/chain.py#L87)).
In this issue, the logging logic should be refactored via implementing additional "default_log" that allow one to write logs only to file (without console dublications).
For details, see this [comment](https://github.com/nccr-itmo/FEDOT/pull/168#discussion_r518117854).

**Comment by BarabanovaIrina** [comment]
https://github.com/nccr-itmo/FEDOT/pull/168#discussion_r518718898
