### ISSUE TITLE
Extend documentation with Fedot chain cases

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#177]
1. Draw schemes that support the available use cases that Fedot' chain maintains (or planning to maintain in future).
2. Add the corresponding new page in documentation.

**Comment by J3FALL** [comment]
Example:
![image](https://user-images.githubusercontent.com/7864250/99378004-fd703100-28d7-11eb-86e9-67b8baf72fee.png)

**Comment by nicl-nno** [comment]
Partially described in 

https://actcognitive.org/platformy/freymvork-generativnogo-avtomaticheskogo-mashinnogo-obucheniya-fedot

**Comment by nicl-nno** [comment]
Obsolete.
