### ISSUE TITLE
Tensorflow < 2.4.0 security issue

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#178]
See dependabot alert: https://github.com/nccr-itmo/FEDOT/network/alert/requirements.txt/tensorflow/open

However, currently tf with version 2.4.0 is not stable, therefore the fix in our project should be implemented later.

**Comment by nicl-nno** [comment]
Это в целом done, но для Python <=3.7 нужно  задать tensorflow>=2.2.0, т.к. 2.1.0 конфликтует с flask.

**Comment by J3FALL** [comment]
Ну, flask в FEDOT не используется по умолчанию, поэтому можно оставить решение этого конфликта для внешних пользователей.

**Comment by nicl-nno** [comment]
Да, но вроде и обновляя tf до 2.2 мы ничего не теряем, он норм и на win и на linux работает. 
Ну или как минимум надо >= поставить.

**Comment by J3FALL** [comment]
ok
