### ISSUE TITLE
[InputData] Support images as InputData 

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#197]
Impement experimental pipeline with simple CNN and image augmentation/preprocessing methods for pattern recognition task:

- New InputData format with generator-based logic (for image batch-reading)
- New simple model (for instance, CNN) that is suitable for pattern recognition
- Several image preprocessing methods
- Example of dataset where pipeline can be applied
- Example of FEDOT pipeline that can solve the given task

**Comment by nicl-nno** [comment]
The code for icebergs images classification from https://github.com/ITMO-NSS-team/nas-fedot can be useful.

Also, I think that MNIST can be used as the simplest example of the images for classification:
https://github.com/jmmanley/conv-autoencoder/blob/master/mnist_test.ipynb
