### ISSUE TITLE
[InputData] Support texts as InputData

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#198]
Impement experimental pipeline with simple NLP-model (or even NaiveBayesClassifier) for text classification/sentiment analysis:

- New InputData format with generator-based logic (for texts batch-loading)
- New simple model (for instance, CNN) or adoptation the existing models that are suitable for text classification
- Maybe bag-of-words, word-2-vec model, etc. for text embeddings
- Several text preprocessing methods (stemming, lemmatization, filtering, etc.)
- Example of dataset where pipeline can be applied (spam classification for instance as the simpliest case)
- Example of FEDOT pipeline that can solve the given task

**Comment by nicl-nno** [comment]
FYI tutorial for AutoNLP

https://www.youtube.com/watch?v=D-taRpi4OJk&ab_channel=AIEngineering
