### ISSUE TITLE
Minor flaws in model export

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#207]
IMO there are several minor issues in the JSON export of the model:

1. "total_chain_types" field is quite confusing
![image](https://user-images.githubusercontent.com/5711814/101794752-3f2b7a80-3b18-11eb-9caf-3752e1ce3a94.png)

"total_chain_models" can be better

2. trained_model_path contains the absolute path. Is it have a reason fronm the reproducibility point of view (since that path becomes non-actual if the folder is moved)? Maybe the relative path is better?

![image](https://user-images.githubusercontent.com/5711814/101794735-3b97f380-3b18-11eb-9fd3-3f415d4d8538.png)

3. The "nodes_from" indices are duplicated if there is only one parent for node

![image](https://user-images.githubusercontent.com/5711814/101794978-7a2dae00-3b18-11eb-82a3-ccdb3a3c0bcf.png)

4. The FileExistsError occurs if the model exports twice with the same file name. The warning and additional index in the file name look comfortable behavior for the user (now the results of the long optimization run can be lost in such case).

**Comment by nicl-nno** [comment]
5. Cache saving incorrectly during export. Example:

def test_fitted_chain_cache_correctness_after_export_and_import():
    train_file_path, test_file_path = get_scoring_case_data_paths()
    train_data = InputData.from_csv(train_file_path)

    json_file_path = 'test_fitted_chain_cache_correctness_after_export_and_import.json'

    if os.path.exists(json_file_path):
        os.remove(json_file_path)

    chain = Chain(PrimaryNode('logit'))
    chain.fit(train_data)

    chain.save_chain(json_file_path)

    new_chain = Chain()
    new_chain.load_chain(json_file_path)

    results = new_chain.fit(train_data)

    os.remove(json_file_path)

    assert results is not None

**Comment by MAGLeb** [comment]
@nicl-nno
Спасибо за качественное ревью и отловленные баги. Со всеми пунктами согласен, только 4-ый вызывает у меня вопросы.
В случае если пользователь хочет сохранить цепочку и вводит уже имеющееся имя файла, верно выбрасывать исключение и тогда данные обученных цепочек не потеряются. В противном случае наоборот, пользователь может затереть JSON со старой цепочкой.

**Comment by nicl-nno** [comment]
Да, но можно создавать файл в стиле saved (2).json - иначе многочасовой запуск пройдет впустую только из-за того, что ты забыл удалить предыдущий файл с тем же именем. Но целом перезапись старого - это тоже кмк вполне ожидаемое поведение.

**Comment by MAGLeb** [comment]
@nicl-nno 
3 пункт не смог воспроизвести. Случай, если только один родитель у ноды. Создал цепочку, но получил верный результат. Пришли пожалуйста весь JSON  или помоги другим образом воспроизвести случай.
