### ISSUE TITLE
Exogen variables as separate primary nodes

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#238]
Instead of passing the exogen variables to chain with input data, it can be passed as a separate input for primary nodes.

Now:
1 InputData (with exogen) -> Chain
Next:
2 InputData (source + exogen) -> Chain -> PrimaryNode1(source) + PrimaryNode2(exogen)

This can be done after #237 will be finished.

**Comment by nicl-nno** [comment]
Не является ли это частью общей задачи по поддержке разнородных типов данных? Ведь там тоже будет возможность подавать несколько источников данных в один узел.

**Comment by J3FALL** [comment]
> Не является ли это частью общей задачи по поддержке разнородных типов данных? Ведь там тоже будет возможность подавать несколько источников данных в один узел.
Да, так и есть, примерно.
2 входных набора данных, но с одним типом, по сути, то же, что ты написал.
Таску ввел, чтобы не забыть убрать эту логику в будущем.
