### ISSUE TITLE
Problem with reading excel file to pandas DataFrame 

### ISSUE THREAD

**Issue by Dreamlone** [nccr-itmo/FEDOT#254]
The problem occurs when trying to run the example in the file "[examples/multiclass_prediction.py](https://github.com/nccr-itmo/FEDOT/blob/master/examples/multiclass_prediction.py)", at the stage of calling the create_multi_clf_examples_from_excel function ([examples/utils.py](https://github.com/nccr-itmo/FEDOT/blob/master/examples/utils.py)). This is because the library that allows you to read excel files is not installed. There is either need to enter it in the requirements.txt, or change the code.

**Comment by nicl-nno** [comment]
We can add smth like this in the script:

try:
    import <excel_library>
except ImportError:
    raise (ImportError, "<excel_library> is not installed on your system. It is required to run this example.")

to avoid the over-complicated requirements.txt
