### ISSUE TITLE
[Utils] project_root() incorrect behaviour

### ISSUE THREAD

**Issue by BarabanovaIrina** [nccr-itmo/FEDOT#258]
Reproducibility:
1. pip install fedot
2. from fedot.core.utils import project_root
3. if __name__ == '__main__':
    print(project_root())

Expected:
/Users/ira/PycharmProjects/FEDOT-benchmarks/

Actual:
/Users/ira/PycharmProjects/FEDOT-benchmarks/**venv/lib/python3.8/site-packages**

Possible solution: 
1. Remove venv/lib/python*/site-packages tale if it is in the path **if this function is intended to be used by user**. 
2. Or rename as fedot_package_parent or smth like that.

**Comment by nicl-nno** [comment]
But is not it ("/Users/ira/PycharmProjects/FEDOT-benchmarks/venv/lib/python3.8/site-packages")
an expected behavior? 

"project_root" is function for the FEDOT project root path, not for root path of any proejct that imports it.

**Comment by BarabanovaIrina** [comment]
Well, I propose to rename as fedot_project_root and modify docstring """Returns project root folder.""", because it confuses.

**Comment by nicl-nno** [comment]
Ok

**Comment by nicl-nno** [comment]
Additional subtask: add test for the fedot_project_root
(use 
![image](https://user-images.githubusercontent.com/5711814/118268829-91593900-b4c6-11eb-87d9-f50d5d5fe3f1.png)
as an example)

**Comment by J3FALL** [comment]
Solved via #295
