### ISSUE TITLE
[Architecture] 

### ISSUE THREAD

**Issue by BarabanovaIrina** [nccr-itmo/FEDOT#287]
Inability to realise some methods for Node on the Node level due to the dependence on Chain: chain object is needed to find edges in the direction from the certain node to the root.
Discovered in https://github.com/nccr-itmo/FEDOT/pull/278#discussion_r621276941

<img width="865" alt="Screenshot 2021-04-28 at 14 43 51" src="https://user-images.githubusercontent.com/29018907/116398156-27873100-a830-11eb-9988-2dd886c455c4.png">

**Comment by nicl-nno** [comment]
Looks outdated and covered by new issues.
