### ISSUE TITLE
API for multi-modal data

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#306]
The user-friendly API should be implemented for the multi-modal datasets. In should be based at existing API.
The rating_prediction case should be refactored to use this API insead of directly usage of the composer.

Also, the processsing of exogeneous time series should be tested (since it is based at same logic)

**Comment by nicl-nno** [comment]
API for time series also should be improved

**Comment by J3FALL** [comment]
Some suggestions for refactoring:
![image](https://user-images.githubusercontent.com/7864250/121355473-96c86880-c938-11eb-9b53-ba166d38df88.png)

![image](https://user-images.githubusercontent.com/7864250/121355539-a3e55780-c938-11eb-920c-699073e393c4.png)
