### ISSUE TITLE
Fix memory leak error during composing

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#308]
In practice, while Composer is working, it generates a lot of Chain objects that reserve Mbs of memory. 
However, most of chains are a short-lived objects and the memory can be released after it has became irrelevant.
The workaround: during the composing a special object can manage the status of the chains that were initialized.

**Comment by nicl-nno** [comment]
Related issue: #183

**Comment by nicl-nno** [comment]
Current situation:

![image](https://user-images.githubusercontent.com/5711814/119703630-66c09600-be5f-11eb-8e2d-8f97d2fa4402.png)

**Comment by nicl-nno** [comment]
After small fixes:

![image](https://user-images.githubusercontent.com/5711814/119703671-72ac5800-be5f-11eb-8cb5-b05492fb7cb1.png)

**Comment by nicl-nno** [comment]
![image](https://user-images.githubusercontent.com/5711814/144667612-101eca57-0a28-4e73-ab85-717a045e9947.png)

Memory leak is here again (

**Comment by nicl-nno** [comment]
Resolved.
