### ISSUE TITLE
Add LightGBM and CatBoost as new Models

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#309]
- Implement new models - LightGBM, Catboost
- Test the performance of Composer with and without the mentioned models
- Discover the default hyperparameters of the models, for instance, check [LAMA ](https://github.com/sberbank-ai-lab/LightAutoML/blob/master/lightautoml/ml_algo/boost_lgbm.py) defaults

**Comment by MAGLeb** [comment]
https://github.com/nccr-itmo/FEDOT/pull/329
