### ISSUE TITLE
Advanced cross-validation

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#326]
Now the cross-validation is quite simple:

- cross-validation should be implemented for tuner
- cross-validation for the time-series should be supported

**Comment by Dreamlone** [comment]
For now, it is finished
PR409 [K-fold cross-validation for tabular data in Tuner implemented](https://github.com/nccr-itmo/FEDOT/pull/409) - cross validation for tabular data for tuner
PR363 [Cross validation methods for time series](https://github.com/nccr-itmo/FEDOT/pull/363)  - cross validation for time series for composer and tuner 
PR292 [Cross validation](https://github.com/nccr-itmo/FEDOT/pull/292) - cross validation for tabular data for composer
