### ISSUE TITLE
Freeze in random_chain generation during composing with specific primary model types

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#341]
In Composer we have initial population generation stage that uses [random_chain](https://github.com/nccr-itmo/FEDOT/blob/ac6f028d37dd3cd6890253b4d8143059687712e7/fedot/core/composer/optimisers/gp_comp/gp_operators.py#L9) function for it. However, if we set `GPComposerRequirements(primary=[data_operations_only])` it will probably freeze due to invalid chain configurations.

It happens due to [chain validation](https://gist.github.com/J3FALL/78148e9ede874baaecf58a206bd7298f): if chain contains more than one identical data_operation in primary_nodes it is invalid.

![image](https://user-images.githubusercontent.com/7864250/123812667-f1802f00-d8fc-11eb-8643-418c1a1ebbb2.png)

Probably, we should improve random_chain function - modify invalid chains if it occurs and log this operation.

**Comment by J3FALL** [comment]
Example of GP requirements that can also reproduce error: 
![image](https://user-images.githubusercontent.com/7864250/123816724-378ac200-d900-11eb-8517-62fca092af16.png)

**Comment by aPovidlo** [comment]
Can’t reproduce this bug in newer version.
