### ISSUE TITLE
Implement sparse lagged operation 

### ISSUE THREAD

**Issue by Dreamlone** [nccr-itmo/FEDOT#348]
The lagged operation turns the original time series into a tabular form. However, with large values of the moving window, there are a lot of features, which does not allow us to quickly train pipelines.

There is a need to implement an operation that would allow selecting certain lags from a lagged table with attributes.

**Comment by nicl-nno** [comment]
Это можно issue же считать закрыым?

**Comment by Dreamlone** [comment]
Ага, эти два PR'а ([370](https://github.com/nccr-itmo/FEDOT/pull/370) и [379](https://github.com/nccr-itmo/FEDOT/pull/379)) решили задачу
