### ISSUE TITLE
Add tests for various data sets to analyze the work of the framework.

### ISSUE THREAD

**Issue by MAGLeb** [nccr-itmo/FEDOT#352]
As a result of this [PR](https://github.com/nccr-itmo/FEDOT/pull/346) was decided to create more tests to measure the work of the framework on various datasets.

**Comment by Dreamlone** [comment]
Due to this three PRs: [508](https://github.com/nccr-itmo/FEDOT/pull/508), [512](https://github.com/nccr-itmo/FEDOT/pull/512) and [515](https://github.com/nccr-itmo/FEDOT/pull/515), many tests have been implemented to check whether the framework runs correctly on the proposed synthetic datasets.
