### ISSUE TITLE
Fedot.fit runs tuning even if with_tuing=False in composer_params

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#361]
In Fedot constructor there is a parameter - _composer_params_ and it is a dictionary with some external params, like learning_time, cv_folds, etc. 
However, if with_tuning is set explicitly, it is still running tuning after composing.

![image](https://user-images.githubusercontent.com/7864250/125348953-9111d880-e365-11eb-8748-2392a17b0935.png)

Example of code how it can be reproduced:
```
def forecast_by_fedot(forecast_length, train_input, predict_input):
    task_parameters = TsForecastingParams(forecast_length=forecast_length)
    model = Fedot(problem='ts_forecasting', task_params=task_parameters,
                  composer_params={'with_tuning': False})
    pipeline = model.fit(features=train_input)
    pipeline.show()
    forecast = model.predict(features=predict_input)

    return forecast
```

P.S. I've running the latest version from master branch

**Comment by nicl-nno** [comment]
Перевел на @v1docq , т.к. это можно пофиксить при обновлении API.

**Comment by v1docq** [comment]
Нашел ошибку в коде, на этапе выбора пресета флаг для тюнера переназначался вне зависимости от флага который мы подавали на входе. Исправил.
