### ISSUE TITLE
Get operations for task it takes a very long time to complete. 15 seconds to parse JSON!!

### ISSUE THREAD

**Issue by MAGLeb** [nccr-itmo/FEDOT#364]
![image](https://user-images.githubusercontent.com/52084975/126029179-02f5c017-dbf5-48b9-8d0d-065d17d7c13f.png)

Also, as I remember when profiled FEDOT see the same time-consuming.

**Comment by nicl-nno** [comment]
Частично это в #327 будет исправлено, т.к. на GPU-производительность это тоже влияет.
