### ISSUE TITLE
Ignoring the choice of mutation types

### ISSUE THREAD

**Issue by Dreamlone** [nccr-itmo/FEDOT#377]
When running the comoposer, if you pass only the mutation type : "parameters change", so that only the hyperparameters in the pipelining nodes change, the algorithm can still insert additional nodes 

Branch: [composing-bug](https://github.com/nccr-itmo/FEDOT/tree/composing-bug)
An example where you can reproduce the described "bug": [composing_with_bug.py](https://github.com/nccr-itmo/FEDOT/blob/composing-bug/examples/composing_with_bug.py)

When you run the example, the parameter_change_mutation function displays the number of nodes in the pipeline. You can see that it sometimes grows.

**Comment by nicl-nno** [comment]
Так кроссовер же все равно применяется  - и он может взять 1 ноду из пайплайна 1 и добавить её к пайплайну 2, получив Pipeline nodes number == 3.

Если добавить crossover_types=[CrossoverTypesEnum.none] - то Pipeline nodes number везде == 2

Мутации вроде правильно выбираются, судя по отладчику.

**Comment by Dreamlone** [comment]
Понял - я об этом механизме не подумал. Решил, что может где-то применять мутация, которая добавляет дополнительные узлы в пайплайн

> Мутации вроде правильно выбираются, судя по отладчику. - Я тоже у себя это наблюдал, поэтому не придумал в чем может быть проблема 

Сорри, что взболомутил эту тему, issue можно закрывать
