### ISSUE TITLE
Window size of composed pipeline can be too large

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#405]
The snippet

`        auto_model = Fedot(problem=problem, timeout=0.2, task_params=TsForecastingParams(forecast_length=14),
                           composer_params={'metric': 'rmse'}, )
        pipeline = auto_model.fit(features=features, target=target)`
        
`        max_lag = \
            round(max([np.ceil(n.custom_params['window_size']) for n
                       in pipeline.nodes if str(n.operation) == 'lagged']))
`

can produce lags with higher length then entire dataset length. 
It make it impossible to estimate the required length of pre-history.

**Comment by Dreamlone** [comment]
Исправлено. Проблема была в том, что параметр исправлялся, но на уровне Operation и Node изменения не доходили, оставаясь на уровне Implementation. 

Теперь при вызове custom_params как get метод - объект напрямую обращается к implementation (уже обученной при этом, если есть возможность).

Изменения в ветке [lagged-max](https://github.com/nccr-itmo/FEDOT/tree/lagged-max), сам "багованный пример" доступен по [ссылке](https://github.com/nccr-itmo/FEDOT/blob/lagged-max/examples/time_series/bug_example.py)
Могу влить изменения в виде маленького PR'а, не против?

**Comment by nicl-nno** [comment]
Вливай конечно.

**Comment by nicl-nno** [comment]
Fixed in #408
