### ISSUE TITLE
RANSAC error at pipeline fitting

### ISSUE THREAD

**Issue by Sash0check** [nccr-itmo/FEDOT#415]
ValueError: RANSAC could not find a valid consensus set. All `max_trials` iterations were skipped because each randomly chosen sub-sample failed the passing criteria. See estimator attributes for diagnostics (n_skips*).
![image](https://user-images.githubusercontent.com/16399597/132097016-d9998f9c-7c8c-4e4f-a993-9bd7c2d1d021.png)

**Comment by nicl-nno** [comment]
After fix workaround in https://github.com/nccr-itmo/FEDOT/pull/424/files/64c4f8315482ecb1c88907adcb7d80504130752d#diff-bfb55318e87be211b23b7c1dee00a6c42cf34e11bac6302ec29f32def3a4c6bb can be removed.
