### ISSUE TITLE
Options to improve design in fedot.api module

### ISSUE THREAD

**Issue by J3FALL** [nccr-itmo/FEDOT#422]
After the [last ](https://github.com/nccr-itmo/FEDOT/pull/416) merge related with API refactoring i found some issues with design.

- Naming in api_utils module
![image](https://user-images.githubusercontent.com/7864250/132676631-cf4f347d-f72c-43cb-ab17-6bf02c1cddaf.png)

I think suffix `*Helper` does not bring much details for the user or developer. In fact, most of the classes _help_ users to do something. In some cases the suffix could be ommited without the loss of meaning: _ApiInitialAssumptionsHelper_ -> _InitialAssumptions_. 
Ofc it's a holy war about naming, but some good points about 'Why Manager/Helper/etc are bad?" can be read [here](https://stackoverflow.com/questions/1866794/naming-classes-how-to-avoid-calling-everything-a-whatevermanager).

- Compositions instead of multiple inheritance

It is also related to the previous example: ApiFacade is derived of several interfaces (ApiDataHelper, ApiComposerHelper, ApiMetricsHelper, ApiInitialAssumptionsHelper). However, ApiComposerHelper is also derived from (ApiMetricsHelper, ApiInitialAssumptionsHelper).
The abstract scheme of classes is like:
![image](https://user-images.githubusercontent.com/7864250/132678382-f2c1a0aa-4489-4e72-8202-45546ee89779.png)

So it looks like a [diamond problem](https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem) and this could be a mess in a future. I suggest to get rid of multiple inheritance here and implement it via composition. 

- Minor typos?

Examples:

![image](https://user-images.githubusercontent.com/7864250/132679448-d52a200d-9e47-4809-b04a-b61b8c67fa07.png)
![image](https://user-images.githubusercontent.com/7864250/132679559-838ad645-b572-4aac-871b-c71dfc80caaa.png)

Maybe it would be useful to add some kind-of pre-commit hooks in order to check PEP issues? Also we could think about our pycharm configuration for formatting and add it to the contribution guide.

**Comment by nicl-nno** [comment]
![image](https://user-images.githubusercontent.com/5711814/133984390-fa6f14c6-6350-456e-a129-8489350768a7.png)

Аlso, obsolet 'chain' naming is still exists.

**Comment by Dreamlone** [comment]
Can we close this issue after pull request #484?

**Comment by J3FALL** [comment]
> Can we close this issue after pull request #484?

Looks like, yes.
