### ISSUE TITLE
Test categorical preprocessing data failed

### ISSUE THREAD

**Issue by Dreamlone** [nccr-itmo/FEDOT#426]
An error occurs when running the test [categorical_preprocessing_unidata](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/api/test_main_api.py#L222)

Common error description: "AttributeError: Too much fitness evaluation errors. Composing stopped."
Possible reason:
![image](https://user-images.githubusercontent.com/52418437/133395716-2c761972-b126-4cbc-ad45-997f02a50e77.png)

**Comment by Dreamlone** [comment]
Важное уточнение, воспроизвести ошибку сложно. Тест упал у меня всего один раз из четырех запусков

**Comment by nicl-nno** [comment]
А сейчас это не починено?

**Comment by Dreamlone** [comment]
Проверил тест в цикле - всё окей, убрал заглушку в #521
