### ISSUE TITLE
ImportError: cannot import name 'train_test_data_setup'

### ISSUE THREAD

**Issue by kurvaraviteja355** [nccr-itmo/FEDOT#452]
When I tried to import the train test data setup it through the error, before i have installed all the requirements but I don't know why am I getting thi error

**Comment by nicl-nno** [comment]
Hello!

Can you provide the example of your script?

**Comment by l-ightmare** [comment]
> When I tried to import the train test data setup it through the error, before i have installed all the requirements but I don't know why am I getting thi error

try 'from fedot.core.data.data_split import train_test_data_setup' , it should resolve your error.

**Comment by nicl-nno** [comment]
I think this issue is outdated and can be closed.
