### ISSUE TITLE
API history folder 

### ISSUE THREAD

**Issue by MAGLeb** [nccr-itmo/FEDOT#464]
If send for composer params:
```
'history_folder': '/some/path'
```
overwise save history to default path _**~/home/user/Fedot/composing_history**_

**Comment by Dreamlone** [comment]
Ага, папку для сохранения истории эволюции теперь можно задавать нормально через api, см. [API presets refactor and minor fixes](https://github.com/nccr-itmo/FEDOT/pull/458)
Бери, если что, FEDOT из этой ветки, я также именно из этой ветки [в модуле для хуавея использую](https://github.com/ITMO-NSS-team/Huawei_AutoML/pull/2)

**Comment by nicl-nno** [comment]
>Сохраняются все-таки пачкой, а не последовательно.
Странно, сохранение ведь в default_on_next_iteration_callback выполняется.

>По сохраненым файлам нельзя понять историю эволюции. Имею ввиду название папок и файлом обезличены и не понятно последовательность.

Числа в название папок - это номера поколений. Может у тебя просто всего одно поколение вычислилось?
