### ISSUE TITLE
ValueError in classification task with regression models

### ISSUE THREAD

**Issue by aPovidlo** [nccr-itmo/FEDOT#506]
```ValueError: Operation svr can not be used as a part of TaskTypesEnum.classification```
This error was raised when the pipeline contains regression models, such as SVR, catboostreg, etc. A possible solution is checking `class decomposes` operation exist in the pipeline and `TaskTypesEnum.classification`, then reg model can be used after this operation.

**Comment by Dreamlone** [comment]
Fixed in #590
