### ISSUE TITLE
Clarify the functionality of the out-of-sample and in-sample functions

### ISSUE THREAD

**Issue by Dreamlone** [nccr-itmo/FEDOT#532]
Using the out-of-sample forecasting function as an example, you can see the noticeable changes in version 0.5. Check pictures in the examples:
* [Version 0.4.1](https://github.com/ITMO-NSS-team/fedot-examples/blob/main/notebooks/version_04_1/5_ts_specific_cases.ipynb)
* [Version 0.5](https://github.com/ITMO-NSS-team/fedot-examples/blob/main/notebooks/latest/5_ts_specific_cases.ipynb) (latest)
![image](https://user-images.githubusercontent.com/52418437/147905836-7b340e10-dd61-465e-9411-7c7f6dfdf590.png)
![image](https://user-images.githubusercontent.com/52418437/147905843-444836c8-2d81-497a-9873-f294e3811124.png)

Need to find out if things work correctly

**Comment by Dreamlone** [comment]
We found out that the random component is contributed by the dtreg model, so this is normal conduct

**Comment by nicl-nno** [comment]
Надо бы в этих примерах зафиксировать seed, чтобы избегжать такого.
