### ISSUE TITLE
Please add CPU only machine support.

### ISSUE THREAD

**Issue by hemangjoshi37a** [nccr-itmo/FEDOT#578]
Please add CPU only machine support.

**Comment by Dreamlone** [comment]
Hi! Please elaborate on what you mean by "CPU only machine support"? The more details you give us about your problem, the sooner we can start working on it

**Comment by hemangjoshi37a** [comment]
Currently the Fedot library can't run in CPU only mahine. I hope it can run
in future.

**Comment by Dreamlone** [comment]
We ran FEDOT on only-CPU servers and had no problems. We have also run framework in containers where there is no access to GPU. Please describe your problem in more detail. The best way is to describe exactly how you ran the framework and what error you encountered

**Comment by nicl-nno** [comment]
Closed since we can't reproduce this problem.
