### ISSUE TITLE
Composer operations combination bug

### ISSUE THREAD

**Issue by ChrisLisbon** [nccr-itmo/FEDOT#580]
Creating composer through ComposerBuilder with custom mutation_types as optimiser_parameters fails with error when MutationTypesEnum.single_drop and MutationTypesEnum.single_edge are in mutation_types together.

![image](https://user-images.githubusercontent.com/44952202/155993257-394d8162-d047-4924-acbd-347dae942151.png)

It can be reproduced by running [fedot\examples\advanced\time_series_forecasting\composing_pipelines.py](https://github.com/nccr-itmo/FEDOT/blob/master/examples/advanced/time_series_forecasting/composing_pipelines.py) with changing 99-100 lines on 
`mutation_types = [MutationTypesEnum.single_drop, MutationTypesEnum.single_edge]`
with any other types.

**Comment by gkirgizov** [comment]
Appears, that Graph class allows for duplicated edges (i.e. `node.nodes_from` can contain duplicate entries), but on removals of nodes, edges etc. only the first occurrence of an edge is removed.
Mutation process sometimes causes such duplicate edges to appear, which leads to ghost `GraphNode` to reappear sometimes.
Fix for #604 must resolve this.
