### ISSUE TITLE
Stopping criteria for the tuner

### ISSUE THREAD

**Issue by IIaKyJIuH** [nccr-itmo/FEDOT#591]
Current [PipelineTuner](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/pipelines/tuning/unified.py#L11) working time depends only on iterations and timeout parameters but some other advanced stopping technics for tuning must be added as well.

**Comment by nicl-nno** [comment]
Но у него же есть поле timeout. Оно игнорируется по факту?

**Comment by nicl-nno** [comment]
FYI https://github.com/hyperopt/hyperopt/issues/449
