### ISSUE TITLE
On entry to DGESDDM parameter number 10 had an illegal value error

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#592]
The following error:
 ** On entry to DGESDDM parameter number 10 had an illegal value 
is raising in various cases.

Example:
Dataset: mfeat-factors
Final pipeline: {'depth': 2, 'length': 2, 'nodes': [lda, poly_features]}

Other example:
Dataset: mfeat-factors
![image](https://user-images.githubusercontent.com/5711814/157847816-8df3f6b4-985f-4944-97fb-1af8edece7d1.png)

**Comment by Dreamlone** [comment]
Add "non-default" tag for LDA model in [PR Timeouts api refactor](https://github.com/nccr-itmo/FEDOT/pull/587)
