### ISSUE TITLE
Visualization of the operations used in pipelines

### ISSUE THREAD

**Issue by Dreamlone** [nccr-itmo/FEDOT#601]
There is a need to keep track of how operations can be used during compositing. It is useful to keep track of what list of models and data operations at different generations is used 

Here are a few concepts of how we can visualize the behavior of the algorithm. The pictures below should be viewed as frames from animations. (left one vs right one)
![image](https://user-images.githubusercontent.com/52418437/158972851-ab4e062b-6cd5-46a6-b572-f7fab5a11a88.png)
Left animation can be prepared like [this video](https://www.youtube.com/watch?v=2wXC3CiuvTQ)

Or static pictures (left one vs right one)
![image](https://user-images.githubusercontent.com/52418437/158972937-67ca8bf0-8b7b-46a3-a653-9ce58a68e8f6.png)

**Comment by MorrisNein** [comment]
Пример анимации для графика 1.
![foo](https://user-images.githubusercontent.com/57573631/164744269-40cc4d65-22c5-481e-ab58-daa8c21df260.gif)

**Comment by MorrisNein** [comment]
> Пример анимации для графика 1.

Добавил плавные переходы, поправил цвета. На этом с улучшением первого типа графиков заканчиваю, перехожу к следующим.
![foo1](https://user-images.githubusercontent.com/57573631/164883044-325cc834-34e4-43bf-9a9e-ad6e04856d73.gif)
