### ISSUE TITLE
Refactor evolutionary optimizer in more modular way

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#608]
Сейчас EvoGraphParameterFreeOptimiser и EvoGraphOptimiser имеют весьма значительное дублирование в коде метода optimise.
Это сильно усложняет их модификацию.

Поэтому есть необходимость в рефакторинге - разделении общей логике ЭА и конкрретных реализацией его частей.

Также можно подумать об улучшении реализации работы с метриками, наборами параметров в parameters и требований в requirements. Например, сейчас поле self.metrics выглядит вообще неиспользуемым.

Пример с использованием внешнего оптимизатора [тут](https://github.com/nccr-itmo/FEDOT/blob/master/examples/advanced/fedot_based_solutions/external_optimizer.py).

**Comment by gkirgizov** [comment]
В целом issue закрыт, остается разве что эта часть:
> наборами параметров в parameters и требований в requirements. 

Есть еще мысль о более модульной организации оптимизатора, но я завел отдельный issue на этот счет #706
