### ISSUE TITLE
DataMerger refactor

### ISSUE THREAD

**Issue by Dreamlone** [nccr-itmo/FEDOT#610]
It is required to revise the structure of DataMerger and prepare separate modules to merge images, texts, specific time series. Existing table and time-series datafusion methods should also be improved. 

What is important to know and take into account:
* Merger must be able to combine tables and texts and pictures in the same pipeline
* Merger must be able to merge tables / texts / images of different tasks (see supplementary_data field in input data)
* I think there will be a lot of tests to implement and it will be necessary to prepare suitable data for them

**Comment by nicl-nno** [comment]
В #583 и #581 затронуты некоторые аспеты этого PR - думаю они скоро войдут в master

**Comment by Dreamlone** [comment]
Добавлю ещё, что при решении этого issue закроется и более специализированный #301
