### ISSUE TITLE
Logger as Singleton

### ISSUE THREAD

**Issue by IIaKyJIuH** [nccr-itmo/FEDOT#622]
Current logger usage suggests passing it through multiple functions/classes and instantiating it there, which is not as comfortable as it could be.

It would have been much intuitive and cleaner if someone had remade the logger according to Singleton pattern.
One could implement different logging directories/logger names as different logger profiles, for example. Also, it would require some sort of multiprocessing sync technics.

**Comment by nicl-nno** [comment]
I think fixes for logging in parralel mode can be considered as a part of this issue:

![image](https://user-images.githubusercontent.com/5711814/169666620-f17d887f-be95-4abf-a68f-a63680d07d08.png)

**Comment by gkirgizov** [comment]
Few other related issues that could be fixed inside this one:
#450
#576
