### ISSUE TITLE
CV test unstable behavior

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#673]
The **test_api_cv_correct** fails in stochastic way:

![image](https://user-images.githubusercontent.com/5711814/166694374-cc4fa938-be30-4500-8325-cf3541aed21f.png)

This behaviour should be reproduced, investigated and fixed.

**Comment by nicl-nno** [comment]
![image](https://user-images.githubusercontent.com/5711814/166882968-79d30e27-40d7-4328-b057-f5627b81aa22.png)

**Comment by gkirgizov** [comment]
I also looked a bit at this. Problem seems to be in `ts_to_table` method on the line 690:
```
    # Remove incomplete rows
    lagged_dataframe.dropna(inplace=True)
```

Because of this it drops different number of rows for `predict` and for `target_columns` in implementations of timeseries operations predict, e.g. in `statsmodels.py` in `AutoRegImplementation`:
```

            _, predict = ts_to_table(idx=old_idx,
                                     time_series=fitted_values,
                                     window_size=forecast_length)

            new_idx, target_columns = ts_to_table(idx=old_idx,
                                                  time_series=target,
                                                  window_size=forecast_length)
```
