### ISSUE TITLE
Set safe_mode = False by default

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#775]
In the current version save_mode is True by default. 
However, it can cause the unexpected quality decrease for user.

May be it's better to use 'false' as default case.

**Comment by valer1435** [comment]
Согласен. Сейчас, благодаря параметру max_pipeline_fit_time FEDOT не уходит в зависания (у себя не заметил пока такого)

**Comment by nicl-nno** [comment]
Большие датасеты openml, судя по всему, иногда зависают (причем насовсем). Но надо перепроверить на текущей версии. Или ты max_pipeline_fit_time  задаешь вручную?

**Comment by valer1435** [comment]
Вручную ставлю на 30 минут, пока ничего не зависло. Но мб пока не встречал тяжелых
