### ISSUE TITLE
Refactoring is_fit_stage logic

### ISSUE THREAD

**Issue by valer1435** [nccr-itmo/FEDOT#822]
Due to single predict method for fi and predict stage methods in implementation become complicated. I propose to change current behaviour by dividing method predict on two methods `predict `and `predict_for_fit `.

**Comment by nicl-nno** [comment]
А predict_for_fit будет нужен только как приватный метод, используемый внутри реализации fit-а?

**Comment by valer1435** [comment]
Можно сделать его приватным, но он по идее будет использоваться в методе fit у пайплайна, вместо прокидывания постоянно булевской переменной
