### ISSUE TITLE
Enable separate cache DBs for separate FEDOT instances

### ISSUE THREAD

**Issue by IIaKyJIuH** [nccr-itmo/FEDOT#824]
Currently there is no way to use caching while running two or more separate instances of FEDOT simultaneously, cause they are deleting each others database files.

So it is common to see something like
![image](https://user-images.githubusercontent.com/38308131/184943441-61684d74-aac8-4d00-931f-e90086e3a1e3.png)

The problem is in [this caching db class method](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/caching/base_cache_db.py#L81-L86). It was created in order to free memory on a hard disk from the old db files.

It is required to propose some solution that will still be cleaning up the memory after running FEDOT and at the same time it won't influence on the separate runs.

**Comment by nicl-nno** [comment]
А если в рамках каждой сессии использовать уникальные имена таблиц (operations+uuid) - это в первом приближении не решит проблему?

**Comment by IIaKyJIuH** [comment]
Правильно ли я понял, ты имеешь в виду работу всех процессов и инстансов Федота над одной БД, но сделать внутри уникальные таблицы на каждую сессию?

Если так, то всё равно не очень понятно, как этот файл с БД очищать в случае, когда там накопится уже много таблиц от предыдущих сессий.

Вообще бы так сделать, чтобы по завершении работы Федота он удалял все файлы, которые сгенерил, если пути к ним не были заданы пользователем

**Comment by nicl-nno** [comment]
Да, вроде того.

Ну, можно смотреть по последней дате активности с этой таблицей. Ну и действительно по зарвешении работы очищать всё, что создано текущей сессией (но это только для корректного завершения сработает).

**Comment by valer1435** [comment]
> Правильно ли я понял, ты имеешь в виду работу всех процессов и инстансов Федота над одной БД, но сделать внутри уникальные таблицы на каждую сессию?
> 
> Если так, то всё равно не очень понятно, как этот файл с БД очищать в случае, когда там накопится уже много таблиц от предыдущих сессий.
> 
> Вообще бы так сделать, чтобы по завершении работы Федота он удалял все файлы, которые сгенерил, если пути к ним не были заданы пользователем

Они же по идее лежат в одной  папке. Можно чистить по префиксу

**Comment by IIaKyJIuH** [comment]
> Они же по идее лежат в одной папке. Можно чистить по префиксу

[В текущем раскладе](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/caching/base_cache_db.py#L25) префикс всегда не предугадаешь

А вот по дате можно было бы чистить со сроком >1 дня, норм? И учесть ещё, что это не заданный пользователем путь, а tmp директория

**Comment by nicl-nno** [comment]
Ну в теории запуск automl может заниматься больше одного дня. Те что не относятся к текущему запуску - в целом да, можно чистить.
