### ISSUE TITLE
test_auto_preset_converted_correctly fails when the PC performance is quite high

### ISSUE THREAD

**Issue by andreygetmanov** [nccr-itmo/FEDOT#827]
In this test the 'auto' preset in FEDOT API is choosing between 'best quality' and 'fast train' presets depending on the fit time. Timeout is set to 0.01 min to avoid the choice of 'best quality' preset. However, if the PC is quite fast, this timeout is too high. On my machine (8xi7-9700 CPU @ 3.00GHz, 32 Gb RAM, Manjaro Linux) fails in 99% times with timeout = 0.01 and in 0% times with timeout = 0.005.
Maybe let's make the timeout lower?

**Comment by nicl-nno** [comment]
Забавно. Ну давайте сделаем lowe, если поможет.

**Comment by MorrisNein** [comment]
Имеет смысл сделать его `1e-5` для мегасупердуперкомпьютеров? Или мб протестить с timeout = 0
