### ISSUE TITLE
Improve parallel evaluation for composer

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT#840]
The are several problems in the current implementation of parallelization:

1) High memory comsumprion (is it correct?)
2) leaked semaphore bug https://bugs.python.org/issue46391
3) Nested processes creating used to limit the max execution time

Possible solutions: change multiprocessing lib to (1) joblib or (2) ray

**Comment by valer1435** [comment]
У меня после завершения скрипта в мультипроцессорном режиме остаются какие-то процессы, которые к тому же и держат лог и не дают в него писать

**Comment by gkirgizov** [comment]
@nicl-nno можно ли считать баг закрытым после PR @valer1435 ?

**Comment by nicl-nno** [comment]
Давай пока закроем. Если всплывут проблемы с памятью - открою снова.
