### ISSUE TITLE
Abstract OptHistory to be usable for generic Graphs

### ISSUE THREAD

**Issue by gkirgizov** [nccr-itmo/FEDOT#866]
The idea is to abstract all mentions of the Pipeline.

Subtasks:
- [x] refactor `save_current_results` to work on Individuals & Graph.save
  - also better drop `additional_info`, possibly make Individual Serializable
- [x] remove PipelineTemplate usages
- [x] pass Adapter at init (instead of manually constructing PipelineAdapter)
- [ ] https://github.com/nccr-itmo/FEDOT/issues/846
- [ ] Implement some tests for using OptHistory with custom mock graphs
- [x] #901 

Such abstracted history will be quite useful for EPDE & BAMT & others -- they will get history functionality for free.
Possibly this will allow to easily implement something like FEDOT.Web - style UI (for generic evolution history) on top of this as the next step

**Comment by nicl-nno** [comment]
Если мы хотим большей универсальности, то надо поддерживать достаточно произвольные переходы между поколениями.

Как минимум: нужна возможность делать пометки, которые бы объясняли семантику "поколения" - вида "Tuning", "SA", etc.

Как максимум: такие переходы должны быть показаны как операторы (не обязательно эволюционные).

**Comment by MorrisNein** [comment]
Добавил #901 в список
